#####################################################################
#
#  RainFARM configuration file
#
# About: configuration file for ESMValTool RainFARM namelist.
#
#####################################################################

# Pre-processing options
rgrid   <-  "r320x160"       # set FALSE or desired regridding resolution (e.g., comparing different datasets)  
rlonlatdata <- c(9,13,44,48) # region where calculation is to be performed. The region selected needs 
                             # to have equal number of longitude and latitude grid points. 
                             # Warning: downcaling can reach very high resolution so select limited area.  
                             # NOTE: lon(0/360) 

# RainFARM options 
# Note - RainFARM usage:  rfarm [-s SLOPE] [-e NENS] [-n NF] [-r REGION] [-w WEIGHTS]
#                               [-o OUTFILE] [-v VARNAME] [-g] [-c]
# set FALSE to void argument
slope = 1.7         # spatial spectral slope
nens = 2            # number of ensemble members to be calculated
nf = 2              # subdivisions for downscaling
weights_climo =     # climatology file to be used to calculate weights (calling rfweights) 
          "/work/datasets/climate/WORLDCLIM/prec/prec_06_16_central_europe.nc" 
varname = F         # input variable name - this is assigned by ESMValTool pre-processing 
conserv_glob = F    # conserve precipitation over full domain
conserv_smooth = T  # conserve precipitation using convolution

#(outfile is generated by rainfarm.r based on the input file)
rainfarm_args=list(slope=slope,nens=nens,nf=nf,weights_climo=weights_climo,varname=varname,
                   conserv_glob=conserv_glob,conserv_smooth=conserv_smooth)
rainfarm_options=list("-s","-e","-n","-w","-v","-g","-c")

# NOTE: for more information type 'rfarm -h' from terminal
